name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - run: pip install -e .[dev]
    - run: isort --check-only libcoveweb2 setup.py
    - run: black --check libcoveweb2 setup.py
    - run: flake8 libcoveweb2 setup.py
    - run: mypy --install-types --non-interactive -p libcoveweb2
